name: Deploy
on:
  push:
    branches: ["develop"] # main 브랜치에 push 발생하면 트리거
  pull_request:
    branches: ["develop"]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: lts/Hydrogen

      - name: Cache node modules
        uses: actions/cache@v2.1.8
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd client
          npm install
          npm install react-scripts --save
          echo "dependencies 오류"

      - name: Build
        run: |
          cd client
          npm install 
          npm run build
          echo "run build 오류"  

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ohsul-fe
          

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted
    steps:
      - name: Pull and restart Docker Container
        run: |
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ohsul-fe
          docker stop ohsul-fe || true
          docker run -d --rm --name ohsul-fe -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/ohsul-fe
