name: Deploy
on:
  push:
    branches: ["develop"] 
  pull_request:
    branches: ["develop"]

jobs:
  build-docker-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: lts/Hydrogen

      - name: Cache node modules
        uses: actions/cache@v2.1.8
        id: cache
        with:
          path: node_modules
          key: npm-packages-${{ hashFiles('**/package-lock.json') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          cd client
          npm install
          npm install react-scripts --save

      - name: Build
        run: |
          cd client
          npm install 
          npm run build

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/ohsul-fe

  run-docker-image-on-ec2:
    needs: build-docker-image
    runs-on: self-hosted

    steps:          
      # 1. 최신 이미지를 풀받습니다
      - name: docker pull
        run: sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/ohsul-fe

      # 2. 기존의 컨테이너를 중지시킵니다
      - name: docker stop container
        run: sudo docker stop ohsul-fe || true

      # 3. 최신 이미지를 컨테이너화하여 실행시킵니다
      - name: docker run new container
        run: sudo docker run --name ohsul-fe -v /etc/letsencrypt:/etc/letsencrypt --rm -d -p 80:80 -p 443:443 -e REACT_APP_KAKAOMAP_KEY=${{secrets.REACT_APP_KAKAOMAP_KEY}} ${{ secrets.DOCKERHUB_USERNAME }}/ohsul-fe

      # 4. 미사용 이미지를 정리합니다
      - name: delete old docker image
        run: sudo docker system prune -f
